- name: 'Build and run Docker image'
  hosts: localhost
  tasks:
    - name: Get Jenkins build number
      command: 'echo $BUILD_NUMBER'
      register: build_number
      
    - name: Build Docker image
      command: 'docker build -t purdue-igp-docker:latest .'
      command: 'docker tag purdue-igp-docker:latest divsdevi/purdue-igp-docker:latest'


    - name: Run in container
      command: 'docker run -d --rm --name "purdi" -p 8088:8080 divsdevi/purdue-igp-docker:latest'      
   
