- name: 'Build and run Docker image'
  hosts: localhost
  tasks:
    - name: Get Jenkins build number
      command: 'echo $BUILD_NUMBER'
      register: build_number
      
    - name: Build Docker image
      command: 'docker build -t purdue-igp-docker .'
      command: 'docker tag purdue-igp-docker:$BUILD_NUMBER divsdevi/purdue-igp-docker:$BUILD_NUMBER'

    

    - name: Run in container
      command: 'docker run -d --rm --name "purd" -p 8085:8080 divsdevi/purdue-igp-docker'      
   
