- name: 'Build and run Docker image'
  hosts: localhost
  tasks:
    - name: Get Jenkins build number
      command: 'echo $BUILD_NUMBER'
      register: build_number
      
    - name: Build Docker image
      command: 'docker build -t purdue-igp-docker .'

    
    
    - name: Run in container
      command: 'docker run -d --rm --name "pur" -p 8084:8080 divsdevi/purdue-igp-docker'      
   
